/**
 * Seed script for 200 JLPT N1 grammar patterns.
 * Run with: npx tsx scripts/seed-grammar.ts
 */

import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import { grammarPoints, type InsertGrammarPoint } from "../shared/schema";

const n1GrammarPatterns: InsertGrammarPoint[] = [
  // ============================================================================
  // Formal / Literary Expressions (1-25)
  // ============================================================================
  {
    id: "n1-001",
    pattern: "～あっての",
    meaning: "only because of; owing to",
    meaningJp: "～があるからこそ",
    example: "家族あっての幸せだ。",
    exampleTranslation: "Happiness exists only because of family.",
    category: "formal",
    relatedPatterns: ["n1-002"],
  },
  {
    id: "n1-002",
    pattern: "～いかんで/いかんによっては",
    meaning: "depending on",
    meaningJp: "～次第で",
    example: "結果いかんで、対応を決める。",
    exampleTranslation: "We will decide the response depending on the results.",
    category: "conditional",
    relatedPatterns: ["n1-001"],
  },
  {
    id: "n1-003",
    pattern: "～いかんにかかわらず",
    meaning: "regardless of",
    meaningJp: "～に関係なく",
    example: "理由いかんにかかわらず、遅刻は許されない。",
    exampleTranslation: "Regardless of the reason, being late is not permitted.",
    category: "formal",
    relatedPatterns: ["n1-002"],
  },
  {
    id: "n1-004",
    pattern: "～う/ようが～まいが",
    meaning: "whether... or not",
    meaningJp: "～ても～なくても",
    example: "雨が降ろうが降るまいが、出かける。",
    exampleTranslation: "Whether it rains or not, I'm going out.",
    category: "conditional",
    relatedPatterns: ["n1-005"],
  },
  {
    id: "n1-005",
    pattern: "～う/ようと(も)",
    meaning: "even if; no matter how",
    meaningJp: "たとえ～ても",
    example: "何があろうと、諦めない。",
    exampleTranslation: "No matter what happens, I won't give up.",
    category: "conditional",
    relatedPatterns: ["n1-004"],
  },
  {
    id: "n1-006",
    pattern: "～かぎりだ",
    meaning: "extremely; to the utmost degree",
    meaningJp: "非常に～だ",
    example: "嬉しいかぎりだ。",
    exampleTranslation: "I am extremely happy.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-007",
    pattern: "～がてら",
    meaning: "while; on the occasion of",
    meaningJp: "～のついでに",
    example: "散歩がてら、買い物に行く。",
    exampleTranslation: "I'll go shopping while taking a walk.",
    category: "conjunctive",
    relatedPatterns: ["n1-008"],
  },
  {
    id: "n1-008",
    pattern: "～かたがた",
    meaning: "at the same time; while also",
    meaningJp: "～を兼ねて",
    example: "お礼かたがた、お伺いします。",
    exampleTranslation: "I will visit while also expressing my thanks.",
    category: "formal",
    relatedPatterns: ["n1-007"],
  },
  {
    id: "n1-009",
    pattern: "～かたわら",
    meaning: "while; alongside",
    meaningJp: "～一方で",
    example: "働くかたわら、学校に通っている。",
    exampleTranslation: "While working, I'm also attending school.",
    category: "conjunctive",
    relatedPatterns: [],
  },
  {
    id: "n1-010",
    pattern: "～が早いか",
    meaning: "as soon as; the moment",
    meaningJp: "～とすぐに",
    example: "ベルが鳴るが早いか、生徒たちは教室を飛び出した。",
    exampleTranslation: "The moment the bell rang, the students rushed out of the classroom.",
    category: "temporal",
    relatedPatterns: ["n1-011", "n1-012"],
  },
  {
    id: "n1-011",
    pattern: "～なり",
    meaning: "as soon as; the moment",
    meaningJp: "～とすぐに",
    example: "彼は部屋に入るなり、倒れてしまった。",
    exampleTranslation: "The moment he entered the room, he collapsed.",
    category: "temporal",
    relatedPatterns: ["n1-010", "n1-012"],
  },
  {
    id: "n1-012",
    pattern: "～や否や",
    meaning: "as soon as; no sooner than",
    meaningJp: "～とすぐに",
    example: "ドアを開けるや否や、猫が飛び出してきた。",
    exampleTranslation: "No sooner had I opened the door than the cat jumped out.",
    category: "temporal",
    relatedPatterns: ["n1-010", "n1-011"],
  },
  {
    id: "n1-013",
    pattern: "～極まる/極まりない",
    meaning: "extremely; utterly",
    meaningJp: "非常に～だ",
    example: "失礼極まりない態度だ。",
    exampleTranslation: "That is an utterly rude attitude.",
    category: "emphasis",
    relatedPatterns: ["n1-006"],
  },
  {
    id: "n1-014",
    pattern: "～ごとき/ごとく",
    meaning: "like; as if",
    meaningJp: "～のような",
    example: "彼女は花のごとき美しさだ。",
    exampleTranslation: "She has beauty like a flower.",
    category: "classical",
    relatedPatterns: [],
  },
  {
    id: "n1-015",
    pattern: "～こととて",
    meaning: "because; since (formal excuse)",
    meaningJp: "～ことなので",
    example: "不慣れなこととて、失礼がありましたらお許しください。",
    exampleTranslation: "Since I am inexperienced, please forgive any rudeness.",
    category: "formal",
    relatedPatterns: [],
  },
  {
    id: "n1-016",
    pattern: "～始末だ",
    meaning: "end up; result in (negative)",
    meaningJp: "ついに～という悪い結果になった",
    example: "借金を重ね、ついに破産する始末だ。",
    exampleTranslation: "Piling up debts, he ended up going bankrupt.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-017",
    pattern: "～ずにはおかない/ないではおかない",
    meaning: "cannot help but; inevitably",
    meaningJp: "必ず～させる",
    example: "この映画は観客を感動させずにはおかない。",
    exampleTranslation: "This movie inevitably moves the audience.",
    category: "emphasis",
    relatedPatterns: ["n1-018"],
  },
  {
    id: "n1-018",
    pattern: "～ずにはすまない/ないではすまない",
    meaning: "must; cannot avoid",
    meaningJp: "～しなければならない",
    example: "謝らずにはすまない。",
    exampleTranslation: "I must apologize.",
    category: "emphasis",
    relatedPatterns: ["n1-017"],
  },
  {
    id: "n1-019",
    pattern: "～たりとも～ない",
    meaning: "not even; not a single",
    meaningJp: "一つも～ない",
    example: "一秒たりとも無駄にしたくない。",
    exampleTranslation: "I don't want to waste even a single second.",
    category: "negative",
    relatedPatterns: [],
  },
  {
    id: "n1-020",
    pattern: "～たるもの",
    meaning: "those who are; as befitting",
    meaningJp: "～という立場にある者は",
    example: "教師たるもの、模範を示すべきだ。",
    exampleTranslation: "Those who are teachers should set an example.",
    category: "formal",
    relatedPatterns: [],
  },
  {
    id: "n1-021",
    pattern: "～っぱなし",
    meaning: "leaving in a state; keep doing",
    meaningJp: "～したまま",
    example: "テレビをつけっぱなしにしないで。",
    exampleTranslation: "Don't leave the TV on.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-022",
    pattern: "～てからというもの",
    meaning: "ever since",
    meaningJp: "～てから（ずっと）",
    example: "日本に来てからというもの、毎日日本語を勉強している。",
    exampleTranslation: "Ever since coming to Japan, I've been studying Japanese every day.",
    category: "temporal",
    relatedPatterns: [],
  },
  {
    id: "n1-023",
    pattern: "～てこそ",
    meaning: "only after; precisely because",
    meaningJp: "～して初めて",
    example: "失敗してこそ、学べることがある。",
    exampleTranslation: "Only after failing can you learn certain things.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-024",
    pattern: "～であれ/であろうと",
    meaning: "even if; no matter",
    meaningJp: "たとえ～でも",
    example: "誰であれ、ルールを守らなければならない。",
    exampleTranslation: "No matter who you are, you must follow the rules.",
    category: "conditional",
    relatedPatterns: ["n1-005"],
  },
  {
    id: "n1-025",
    pattern: "～ときたら",
    meaning: "speaking of; when it comes to",
    meaningJp: "～について言えば",
    example: "うちの子ときたら、全然勉強しない。",
    exampleTranslation: "Speaking of my child, they don't study at all.",
    category: "emphasis",
    relatedPatterns: [],
  },

  // ============================================================================
  // Conditional / Hypothetical (26-50)
  // ============================================================================
  {
    id: "n1-026",
    pattern: "～とあれば",
    meaning: "if it is the case that; when",
    meaningJp: "～という状況なら",
    example: "君のためとあれば、何でもする。",
    exampleTranslation: "If it's for you, I'll do anything.",
    category: "conditional",
    relatedPatterns: [],
  },
  {
    id: "n1-027",
    pattern: "～とあって",
    meaning: "because; since (special occasion)",
    meaningJp: "～という状況なので",
    example: "連休とあって、どこも混んでいる。",
    exampleTranslation: "Since it's a holiday, everywhere is crowded.",
    category: "causative",
    relatedPatterns: [],
  },
  {
    id: "n1-028",
    pattern: "～といい～といい",
    meaning: "whether... or...; both... and...",
    meaningJp: "～も～も",
    example: "味といい見た目といい、完璧な料理だ。",
    exampleTranslation: "Both in taste and appearance, it's a perfect dish.",
    category: "comparative",
    relatedPatterns: [],
  },
  {
    id: "n1-029",
    pattern: "～といえども",
    meaning: "even though; although",
    meaningJp: "～であっても",
    example: "子供といえども、責任がある。",
    exampleTranslation: "Even though they are children, they have responsibility.",
    category: "conditional",
    relatedPatterns: [],
  },
  {
    id: "n1-030",
    pattern: "～といったらない/といったらありはしない",
    meaning: "extremely; indescribably",
    meaningJp: "非常に～だ",
    example: "嬉しいといったらない。",
    exampleTranslation: "I am indescribably happy.",
    category: "emphasis",
    relatedPatterns: ["n1-006", "n1-013"],
  },
  {
    id: "n1-031",
    pattern: "～ところを",
    meaning: "when; while (interruption)",
    meaningJp: "～している時に",
    example: "お忙しいところを申し訳ありません。",
    exampleTranslation: "I'm sorry to bother you while you're busy.",
    category: "temporal",
    relatedPatterns: [],
  },
  {
    id: "n1-032",
    pattern: "～とは",
    meaning: "to think that; the fact that",
    meaningJp: "～なんて",
    example: "彼が優勝するとは思わなかった。",
    exampleTranslation: "I didn't think he would win.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-033",
    pattern: "～とはいえ",
    meaning: "although; even though",
    meaningJp: "～けれども",
    example: "春とはいえ、まだ寒い。",
    exampleTranslation: "Although it's spring, it's still cold.",
    category: "conditional",
    relatedPatterns: ["n1-029"],
  },
  {
    id: "n1-034",
    pattern: "～ともあろう",
    meaning: "such a... as; for someone of the status of",
    meaningJp: "～のような立場の人が",
    example: "社長ともあろう人が、そんなことを言うとは。",
    exampleTranslation: "For someone of the status of company president to say such a thing...",
    category: "formal",
    relatedPatterns: ["n1-020"],
  },
  {
    id: "n1-035",
    pattern: "～ともなく/ともなしに",
    meaning: "without particularly intending to",
    meaningJp: "特に～するつもりもなく",
    example: "見るともなくテレビを見ていた。",
    exampleTranslation: "I was watching TV without really intending to.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-036",
    pattern: "～ともなると/ともなれば",
    meaning: "when it comes to; if it is",
    meaningJp: "～という段階になると",
    example: "大学生ともなると、自立が求められる。",
    exampleTranslation: "When you become a university student, independence is expected.",
    category: "conditional",
    relatedPatterns: [],
  },
  {
    id: "n1-037",
    pattern: "～ないではいられない",
    meaning: "cannot help but; cannot resist",
    meaningJp: "～せずにはいられない",
    example: "笑わないではいられなかった。",
    exampleTranslation: "I couldn't help but laugh.",
    category: "emphasis",
    relatedPatterns: ["n1-017"],
  },
  {
    id: "n1-038",
    pattern: "～ないまでも",
    meaning: "even if not; though not",
    meaningJp: "～しなくても",
    example: "完璧でないまでも、努力はした。",
    exampleTranslation: "Even if not perfect, I made an effort.",
    category: "conditional",
    relatedPatterns: [],
  },
  {
    id: "n1-039",
    pattern: "～ながらに/ながらにして",
    meaning: "while remaining; from the start",
    meaningJp: "～のままで",
    example: "生まれながらにして才能がある。",
    exampleTranslation: "They have talent from birth.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-040",
    pattern: "～なくして(は)",
    meaning: "without; unless there is",
    meaningJp: "～がなければ",
    example: "努力なくして成功はない。",
    exampleTranslation: "There is no success without effort.",
    category: "conditional",
    relatedPatterns: [],
  },
  {
    id: "n1-041",
    pattern: "～なしに(は)",
    meaning: "without",
    meaningJp: "～がなくては",
    example: "彼の助けなしには完成できなかった。",
    exampleTranslation: "Without his help, I couldn't have completed it.",
    category: "conditional",
    relatedPatterns: ["n1-040"],
  },
  {
    id: "n1-042",
    pattern: "～ならでは",
    meaning: "unique to; only possible with",
    meaningJp: "～だからこそ",
    example: "京都ならではの風景だ。",
    exampleTranslation: "This is scenery unique to Kyoto.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-043",
    pattern: "～なり～なり",
    meaning: "either... or...; such as",
    meaningJp: "～とか～とか",
    example: "電話なりメールなり、連絡してください。",
    exampleTranslation: "Please contact me by phone or email.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-044",
    pattern: "～なりに/なりの",
    meaning: "in one's own way; according to",
    meaningJp: "それ相応に",
    example: "子供なりに考えている。",
    exampleTranslation: "They're thinking about it in their own childlike way.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-045",
    pattern: "～にあって",
    meaning: "in; at (situation)",
    meaningJp: "～の状況において",
    example: "危機的状況にあって、冷静さを失わない。",
    exampleTranslation: "In a critical situation, don't lose your composure.",
    category: "formal",
    relatedPatterns: [],
  },
  {
    id: "n1-046",
    pattern: "～にあたって/にあたり",
    meaning: "on the occasion of; when",
    meaningJp: "～に際して",
    example: "開会にあたり、ご挨拶申し上げます。",
    exampleTranslation: "On the occasion of the opening, I would like to greet you.",
    category: "formal",
    relatedPatterns: [],
  },
  {
    id: "n1-047",
    pattern: "～に至って(は)/に至っても",
    meaning: "now that; even at this point",
    meaningJp: "～の段階になって",
    example: "この段階に至っては、引き返せない。",
    exampleTranslation: "Now that we've reached this stage, we can't turn back.",
    category: "temporal",
    relatedPatterns: [],
  },
  {
    id: "n1-048",
    pattern: "～に至る",
    meaning: "to come to; to lead to",
    meaningJp: "～という結果になる",
    example: "交渉は決裂に至った。",
    exampleTranslation: "The negotiations came to a breakdown.",
    category: "other",
    relatedPatterns: ["n1-047"],
  },
  {
    id: "n1-049",
    pattern: "～にかかわる",
    meaning: "concerning; relating to",
    meaningJp: "～に関係する",
    example: "命にかかわる問題だ。",
    exampleTranslation: "It's a matter of life and death.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-050",
    pattern: "～にかこつけて",
    meaning: "using as an excuse; under the pretext of",
    meaningJp: "～を口実にして",
    example: "出張にかこつけて、観光を楽しんだ。",
    exampleTranslation: "Using the business trip as an excuse, I enjoyed sightseeing.",
    category: "other",
    relatedPatterns: [],
  },

  // ============================================================================
  // Emphasis / Degree (51-75)
  // ============================================================================
  {
    id: "n1-051",
    pattern: "～にかたくない",
    meaning: "not hard to; easy to",
    meaningJp: "～するのは難しくない",
    example: "彼の気持ちは想像にかたくない。",
    exampleTranslation: "It's not hard to imagine his feelings.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-052",
    pattern: "～に堪えない",
    meaning: "unbearable; cannot endure",
    meaningJp: "～することができない",
    example: "その光景は見るに堪えない。",
    exampleTranslation: "That sight is unbearable to watch.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-053",
    pattern: "～に足る/に足りる",
    meaning: "worthy of; sufficient for",
    meaningJp: "～する価値がある",
    example: "信頼に足る人物だ。",
    exampleTranslation: "They are a person worthy of trust.",
    category: "formal",
    relatedPatterns: [],
  },
  {
    id: "n1-054",
    pattern: "～にひきかえ",
    meaning: "in contrast to; unlike",
    meaningJp: "～と比べて",
    example: "姉にひきかえ、妹は活発だ。",
    exampleTranslation: "In contrast to the older sister, the younger one is active.",
    category: "comparative",
    relatedPatterns: [],
  },
  {
    id: "n1-055",
    pattern: "～にもまして",
    meaning: "more than; above all",
    meaningJp: "～以上に",
    example: "何にもまして健康が大切だ。",
    exampleTranslation: "Health is more important than anything.",
    category: "comparative",
    relatedPatterns: [],
  },
  {
    id: "n1-056",
    pattern: "～ぬきに(は)/ぬきで",
    meaning: "without; leaving out",
    meaningJp: "～なしに",
    example: "冗談ぬきで話そう。",
    exampleTranslation: "Let's talk without joking.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-057",
    pattern: "～の至り",
    meaning: "the utmost; the height of",
    meaningJp: "この上なく～だ",
    example: "光栄の至りです。",
    exampleTranslation: "It is the utmost honor.",
    category: "formal",
    relatedPatterns: [],
  },
  {
    id: "n1-058",
    pattern: "～のみならず",
    meaning: "not only; but also",
    meaningJp: "～だけでなく",
    example: "日本のみならず、世界中で人気がある。",
    exampleTranslation: "It's popular not only in Japan but around the world.",
    category: "conjunctive",
    relatedPatterns: [],
  },
  {
    id: "n1-059",
    pattern: "～ばこそ",
    meaning: "precisely because; it is because",
    meaningJp: "～からこそ",
    example: "愛していればこそ、厳しく言う。",
    exampleTranslation: "Precisely because I love you, I say harsh things.",
    category: "emphasis",
    relatedPatterns: ["n1-023"],
  },
  {
    id: "n1-060",
    pattern: "～はおろか",
    meaning: "let alone; not to mention",
    meaningJp: "～はもちろん",
    example: "漢字はおろか、ひらがなも書けない。",
    exampleTranslation: "Let alone kanji, they can't even write hiragana.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-061",
    pattern: "～はさておき",
    meaning: "setting aside; leaving aside",
    meaningJp: "～は別として",
    example: "冗談はさておき、本題に入ろう。",
    exampleTranslation: "Setting aside jokes, let's get to the main topic.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-062",
    pattern: "～ばそれまでだ",
    meaning: "if... then that's the end of it",
    meaningJp: "～たらそれでおしまいだ",
    example: "諦めればそれまでだ。",
    exampleTranslation: "If you give up, that's the end of it.",
    category: "conditional",
    relatedPatterns: [],
  },
  {
    id: "n1-063",
    pattern: "～ひとり～だけでなく",
    meaning: "not only... but also",
    meaningJp: "～だけでなく",
    example: "ひとり日本だけでなく、アジア全体の問題だ。",
    exampleTranslation: "It's not only Japan's problem but all of Asia's.",
    category: "conjunctive",
    relatedPatterns: ["n1-058"],
  },
  {
    id: "n1-064",
    pattern: "～べからざる/べからず",
    meaning: "must not; cannot",
    meaningJp: "～してはいけない",
    example: "入るべからず。",
    exampleTranslation: "Do not enter.",
    category: "negative",
    relatedPatterns: [],
  },
  {
    id: "n1-065",
    pattern: "～べく",
    meaning: "in order to; so as to",
    meaningJp: "～ために",
    example: "合格すべく、毎日勉強した。",
    exampleTranslation: "In order to pass, I studied every day.",
    category: "formal",
    relatedPatterns: [],
  },
  {
    id: "n1-066",
    pattern: "～べくもない",
    meaning: "cannot possibly; there's no way",
    meaningJp: "～することはできない",
    example: "彼に勝つべくもない。",
    exampleTranslation: "There's no way I can beat him.",
    category: "negative",
    relatedPatterns: [],
  },
  {
    id: "n1-067",
    pattern: "～まじき",
    meaning: "should not; unbecoming of",
    meaningJp: "～するべきではない",
    example: "教師にあるまじき行為だ。",
    exampleTranslation: "It's conduct unbecoming of a teacher.",
    category: "negative",
    relatedPatterns: ["n1-064"],
  },
  {
    id: "n1-068",
    pattern: "～までだ/までのことだ",
    meaning: "just; merely; all one can do",
    meaningJp: "ただ～するだけだ",
    example: "失敗したら、やり直すまでだ。",
    exampleTranslation: "If I fail, I'll just try again.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-069",
    pattern: "～までもない",
    meaning: "no need to; not necessary to",
    meaningJp: "～する必要はない",
    example: "言うまでもない。",
    exampleTranslation: "It goes without saying.",
    category: "negative",
    relatedPatterns: [],
  },
  {
    id: "n1-070",
    pattern: "～めく",
    meaning: "to seem like; to show signs of",
    meaningJp: "～らしくなる",
    example: "春めいてきた。",
    exampleTranslation: "It's starting to feel like spring.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-071",
    pattern: "～もさることながら",
    meaning: "not only... but also; while... is important",
    meaningJp: "～も大切だが",
    example: "実力もさることながら、運も必要だ。",
    exampleTranslation: "While ability is important, luck is also necessary.",
    category: "conjunctive",
    relatedPatterns: [],
  },
  {
    id: "n1-072",
    pattern: "～ものを",
    meaning: "if only; although (regret/criticism)",
    meaningJp: "～のに",
    example: "早く言えばいいものを。",
    exampleTranslation: "If only you had said so earlier.",
    category: "conditional",
    relatedPatterns: [],
  },
  {
    id: "n1-073",
    pattern: "～や/や否や",
    meaning: "as soon as; no sooner... than",
    meaningJp: "～するとすぐに",
    example: "起きるや否や、走り出した。",
    exampleTranslation: "As soon as I woke up, I started running.",
    category: "temporal",
    relatedPatterns: ["n1-010", "n1-011"],
  },
  {
    id: "n1-074",
    pattern: "～ゆえ(に)",
    meaning: "because of; due to",
    meaningJp: "～ので",
    example: "若さゆえの過ちだ。",
    exampleTranslation: "It's a mistake due to youth.",
    category: "causative",
    relatedPatterns: [],
  },
  {
    id: "n1-075",
    pattern: "～よう(が/と)～まい(が/と)",
    meaning: "whether... or not",
    meaningJp: "～ても～なくても",
    example: "行こうが行くまいが、君の自由だ。",
    exampleTranslation: "Whether you go or not, it's your choice.",
    category: "conditional",
    relatedPatterns: ["n1-004"],
  },

  // ============================================================================
  // Negative / Prohibition (76-100)
  // ============================================================================
  {
    id: "n1-076",
    pattern: "～をおいて（他に）ない",
    meaning: "there is no... except; only",
    meaningJp: "～以外にない",
    example: "彼をおいて適任者はいない。",
    exampleTranslation: "There is no suitable person except him.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-077",
    pattern: "～を皮切りに",
    meaning: "starting with; beginning from",
    meaningJp: "～を始まりとして",
    example: "東京を皮切りに、全国ツアーを行う。",
    exampleTranslation: "Starting with Tokyo, we will have a nationwide tour.",
    category: "temporal",
    relatedPatterns: [],
  },
  {
    id: "n1-078",
    pattern: "～を禁じ得ない",
    meaning: "cannot help but; cannot suppress",
    meaningJp: "～を抑えることができない",
    example: "涙を禁じ得なかった。",
    exampleTranslation: "I couldn't help but cry.",
    category: "emphasis",
    relatedPatterns: ["n1-037"],
  },
  {
    id: "n1-079",
    pattern: "～を限りに",
    meaning: "as of; starting from (end/limit)",
    meaningJp: "～を最後として",
    example: "今日を限りに禁煙する。",
    exampleTranslation: "Starting from today, I'll quit smoking.",
    category: "temporal",
    relatedPatterns: [],
  },
  {
    id: "n1-080",
    pattern: "～をもって",
    meaning: "with; by means of; as of",
    meaningJp: "～で",
    example: "誠意をもって対応する。",
    exampleTranslation: "I will respond with sincerity.",
    category: "formal",
    relatedPatterns: [],
  },
  {
    id: "n1-081",
    pattern: "～をものともせず",
    meaning: "in spite of; undaunted by",
    meaningJp: "～を問題にせず",
    example: "困難をものともせず、前進した。",
    exampleTranslation: "Undaunted by difficulties, they moved forward.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-082",
    pattern: "～をよそに",
    meaning: "ignoring; in spite of",
    meaningJp: "～を無視して",
    example: "親の心配をよそに、一人暮らしを始めた。",
    exampleTranslation: "Ignoring their parents' worries, they started living alone.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-083",
    pattern: "～を余儀なくされる/させる",
    meaning: "to be forced to; to have no choice but",
    meaningJp: "やむを得ず～する",
    example: "計画の変更を余儀なくされた。",
    exampleTranslation: "We were forced to change the plan.",
    category: "causative",
    relatedPatterns: [],
  },
  {
    id: "n1-084",
    pattern: "～んがため(に)",
    meaning: "in order to",
    meaningJp: "～するために",
    example: "勝たんがために、あらゆる手段を使った。",
    exampleTranslation: "In order to win, they used every means possible.",
    category: "formal",
    relatedPatterns: ["n1-065"],
  },
  {
    id: "n1-085",
    pattern: "～んばかり(に)",
    meaning: "as if; almost",
    meaningJp: "～しそうなほど",
    example: "泣かんばかりに喜んだ。",
    exampleTranslation: "They were so happy, almost to the point of tears.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-086",
    pattern: "～かれ～かれ",
    meaning: "whether... or...; some... others...",
    meaningJp: "～にしろ～にしろ",
    example: "早かれ遅かれ、結果は出る。",
    exampleTranslation: "Sooner or later, results will come out.",
    category: "conditional",
    relatedPatterns: [],
  },
  {
    id: "n1-087",
    pattern: "～しかるべき",
    meaning: "appropriate; proper",
    meaningJp: "当然～するべき",
    example: "しかるべき対応を取る。",
    exampleTranslation: "We will take appropriate action.",
    category: "formal",
    relatedPatterns: [],
  },
  {
    id: "n1-088",
    pattern: "～たところで",
    meaning: "even if; no matter how",
    meaningJp: "たとえ～しても",
    example: "今さら謝ったところで、許さない。",
    exampleTranslation: "Even if you apologize now, I won't forgive you.",
    category: "conditional",
    relatedPatterns: [],
  },
  {
    id: "n1-089",
    pattern: "～たら最後/たが最後",
    meaning: "once... there's no turning back",
    meaningJp: "一度～したら終わりだ",
    example: "手を出したら最後、抜け出せない。",
    exampleTranslation: "Once you get involved, there's no turning back.",
    category: "conditional",
    relatedPatterns: [],
  },
  {
    id: "n1-090",
    pattern: "～つ～つ",
    meaning: "alternating; sometimes... sometimes...",
    meaningJp: "～たり～たり",
    example: "持ちつ持たれつの関係だ。",
    exampleTranslation: "It's a give-and-take relationship.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-091",
    pattern: "～て然るべき",
    meaning: "should; ought to",
    meaningJp: "当然～すべきだ",
    example: "謝って然るべきだ。",
    exampleTranslation: "They should apologize.",
    category: "formal",
    relatedPatterns: ["n1-087"],
  },
  {
    id: "n1-092",
    pattern: "～てなくてなんだろう",
    meaning: "if not... then what is it?",
    meaningJp: "これこそ～だ",
    example: "これが幸せでなくてなんだろう。",
    exampleTranslation: "If this isn't happiness, then what is?",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-093",
    pattern: "～てはかなわない",
    meaning: "cannot stand; cannot bear",
    meaningJp: "～では困る",
    example: "こう暑くてはかなわない。",
    exampleTranslation: "I can't stand it being this hot.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-094",
    pattern: "～てやまない",
    meaning: "sincerely; earnestly",
    meaningJp: "心から～する",
    example: "成功を願ってやまない。",
    exampleTranslation: "I sincerely wish for your success.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-095",
    pattern: "～と相まって",
    meaning: "combined with; together with",
    meaningJp: "～と一緒になって",
    example: "努力と才能が相まって、成功した。",
    exampleTranslation: "Combined with effort and talent, they succeeded.",
    category: "conjunctive",
    relatedPatterns: [],
  },
  {
    id: "n1-096",
    pattern: "～ないものでもない",
    meaning: "not impossible; might be able to",
    meaningJp: "～することもできる",
    example: "頑張れば、合格できないものでもない。",
    exampleTranslation: "If you work hard, it's not impossible to pass.",
    category: "conditional",
    relatedPatterns: [],
  },
  {
    id: "n1-097",
    pattern: "～ながらも",
    meaning: "while; although",
    meaningJp: "～けれども",
    example: "知っていながらも、黙っていた。",
    exampleTranslation: "Although I knew, I remained silent.",
    category: "conditional",
    relatedPatterns: [],
  },
  {
    id: "n1-098",
    pattern: "～なくもない",
    meaning: "not that... isn't; somewhat",
    meaningJp: "～がないわけではない",
    example: "分からなくもないが、賛成できない。",
    exampleTranslation: "It's not that I don't understand, but I can't agree.",
    category: "conditional",
    relatedPatterns: ["n1-096"],
  },
  {
    id: "n1-099",
    pattern: "～にして",
    meaning: "even for; only with (exceptional)",
    meaningJp: "～でさえ",
    example: "天才にして、この問題は解けなかった。",
    exampleTranslation: "Even a genius couldn't solve this problem.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-100",
    pattern: "～にたえない",
    meaning: "cannot bear; cannot stand (formal)",
    meaningJp: "とても～できない",
    example: "感謝の念にたえない。",
    exampleTranslation: "I cannot express enough gratitude.",
    category: "formal",
    relatedPatterns: ["n1-052"],
  },

  // ============================================================================
  // Temporal / Sequence (101-125)
  // ============================================================================
  {
    id: "n1-101",
    pattern: "～に即して/に則して",
    meaning: "in accordance with; following",
    meaningJp: "～に従って",
    example: "法律に即して判断する。",
    exampleTranslation: "We will judge in accordance with the law.",
    category: "formal",
    relatedPatterns: [],
  },
  {
    id: "n1-102",
    pattern: "～にとどまらず",
    meaning: "not limited to; not just",
    meaningJp: "～だけでなく",
    example: "日本にとどまらず、海外でも活躍している。",
    exampleTranslation: "They are active not just in Japan but also overseas.",
    category: "conjunctive",
    relatedPatterns: ["n1-058"],
  },
  {
    id: "n1-103",
    pattern: "～に則る",
    meaning: "to follow; to conform to",
    meaningJp: "～に従う",
    example: "伝統に則る。",
    exampleTranslation: "To follow tradition.",
    category: "formal",
    relatedPatterns: ["n1-101"],
  },
  {
    id: "n1-104",
    pattern: "～の極み",
    meaning: "the height of; the extreme of",
    meaningJp: "この上なく～",
    example: "贅沢の極みだ。",
    exampleTranslation: "It's the height of luxury.",
    category: "emphasis",
    relatedPatterns: ["n1-057"],
  },
  {
    id: "n1-105",
    pattern: "～のなんのって",
    meaning: "extremely; incredibly",
    meaningJp: "非常に～だ",
    example: "暑いのなんのって、倒れそうだった。",
    exampleTranslation: "It was so incredibly hot, I almost collapsed.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-106",
    pattern: "～はいざ知らず",
    meaning: "I don't know about... but; aside from",
    meaningJp: "～は別として",
    example: "昔はいざ知らず、今は違う。",
    exampleTranslation: "I don't know about the past, but it's different now.",
    category: "other",
    relatedPatterns: ["n1-061"],
  },
  {
    id: "n1-107",
    pattern: "～まで(のこと)だ",
    meaning: "just; merely",
    meaningJp: "ただ～だけだ",
    example: "聞いてみるまでだ。",
    exampleTranslation: "I'll just try asking.",
    category: "other",
    relatedPatterns: ["n1-068"],
  },
  {
    id: "n1-108",
    pattern: "～向きがある",
    meaning: "there is a tendency to",
    meaningJp: "～傾向がある",
    example: "最近、景気が上向きだ。",
    exampleTranslation: "Recently, the economy has an upward tendency.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-109",
    pattern: "～も顧みず",
    meaning: "regardless of; without caring about",
    meaningJp: "～を気にせず",
    example: "危険も顧みず、救助に向かった。",
    exampleTranslation: "Regardless of the danger, they headed to rescue.",
    category: "emphasis",
    relatedPatterns: ["n1-081"],
  },
  {
    id: "n1-110",
    pattern: "～をもって/をもちまして",
    meaning: "with this; as of",
    meaningJp: "これで",
    example: "本日をもちまして、閉店いたします。",
    exampleTranslation: "As of today, we will be closing the store.",
    category: "formal",
    relatedPatterns: ["n1-080"],
  },
  {
    id: "n1-111",
    pattern: "～矢先(に)",
    meaning: "just when; on the verge of",
    meaningJp: "まさに～しようとした時",
    example: "出かけようとした矢先に、雨が降り出した。",
    exampleTranslation: "Just when I was about to leave, it started raining.",
    category: "temporal",
    relatedPatterns: [],
  },
  {
    id: "n1-112",
    pattern: "～よりほかない",
    meaning: "have no choice but; can only",
    meaningJp: "～するしかない",
    example: "待つよりほかない。",
    exampleTranslation: "There's no choice but to wait.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-113",
    pattern: "～如何にかかわらず",
    meaning: "regardless of",
    meaningJp: "～に関係なく",
    example: "天候の如何にかかわらず、決行する。",
    exampleTranslation: "Regardless of the weather, we will proceed.",
    category: "formal",
    relatedPatterns: ["n1-003"],
  },
  {
    id: "n1-114",
    pattern: "～が～なら",
    meaning: "if... is..., then",
    meaningJp: "～も～なら",
    example: "親が親なら、子も子だ。",
    exampleTranslation: "Like parent, like child.",
    category: "conditional",
    relatedPatterns: [],
  },
  {
    id: "n1-115",
    pattern: "～きらいがある",
    meaning: "have a tendency to; inclined to",
    meaningJp: "～傾向がある",
    example: "彼は人の話を聞かないきらいがある。",
    exampleTranslation: "He has a tendency not to listen to others.",
    category: "other",
    relatedPatterns: ["n1-108"],
  },
  {
    id: "n1-116",
    pattern: "～ごとし/ごとく",
    meaning: "like; as if (classical)",
    meaningJp: "～のようだ",
    example: "光陰矢の如し。",
    exampleTranslation: "Time flies like an arrow.",
    category: "classical",
    relatedPatterns: ["n1-014"],
  },
  {
    id: "n1-117",
    pattern: "～さぞかし/さぞ",
    meaning: "surely; no doubt",
    meaningJp: "きっと",
    example: "さぞかし大変だったでしょう。",
    exampleTranslation: "It must have been very difficult.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-118",
    pattern: "～すら/さえ",
    meaning: "even (emphasis)",
    meaningJp: "～でさえ",
    example: "彼は挨拶すらしない。",
    exampleTranslation: "He doesn't even greet people.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-119",
    pattern: "～たが早いか",
    meaning: "as soon as",
    meaningJp: "～するとすぐに",
    example: "ドアが開いたが早いか、飛び込んできた。",
    exampleTranslation: "As soon as the door opened, they rushed in.",
    category: "temporal",
    relatedPatterns: ["n1-010"],
  },
  {
    id: "n1-120",
    pattern: "～だけましだ",
    meaning: "at least; better than nothing",
    meaningJp: "～だけでも良い",
    example: "怪我がなかっただけましだ。",
    exampleTranslation: "At least there were no injuries.",
    category: "comparative",
    relatedPatterns: [],
  },
  {
    id: "n1-121",
    pattern: "～たる",
    meaning: "being; as (formal modifier)",
    meaningJp: "～である",
    example: "国民たる義務を果たす。",
    exampleTranslation: "To fulfill one's duty as a citizen.",
    category: "formal",
    relatedPatterns: ["n1-020"],
  },
  {
    id: "n1-122",
    pattern: "～でなくてなんだろう",
    meaning: "if not... then what is it?",
    meaningJp: "まさに～だ",
    example: "これが愛でなくてなんだろう。",
    exampleTranslation: "If this isn't love, then what is?",
    category: "emphasis",
    relatedPatterns: ["n1-092"],
  },
  {
    id: "n1-123",
    pattern: "～というところだ/といったところだ",
    meaning: "roughly speaking; approximately",
    meaningJp: "だいたい～だ",
    example: "参加者は100人というところだ。",
    exampleTranslation: "There are roughly 100 participants.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-124",
    pattern: "～とは裏腹に",
    meaning: "contrary to; in spite of",
    meaningJp: "～とは反対に",
    example: "本心とは裏腹に、笑顔を見せた。",
    exampleTranslation: "Contrary to their true feelings, they showed a smile.",
    category: "comparative",
    relatedPatterns: [],
  },
  {
    id: "n1-125",
    pattern: "～ないことには",
    meaning: "unless; if not",
    meaningJp: "～しなければ",
    example: "やってみないことには、分からない。",
    exampleTranslation: "Unless you try, you won't know.",
    category: "conditional",
    relatedPatterns: [],
  },

  // ============================================================================
  // Miscellaneous / Other (126-150)
  // ============================================================================
  {
    id: "n1-126",
    pattern: "～ならいざ知らず",
    meaning: "if it were... perhaps, but",
    meaningJp: "～なら分かるが",
    example: "冗談ならいざ知らず、本気で言っているのか。",
    exampleTranslation: "If it were a joke, perhaps, but are you serious?",
    category: "conditional",
    relatedPatterns: ["n1-106"],
  },
  {
    id: "n1-127",
    pattern: "～にひきかえ",
    meaning: "in contrast to",
    meaningJp: "～に比べて",
    example: "去年にひきかえ、今年は暖かい。",
    exampleTranslation: "In contrast to last year, this year is warm.",
    category: "comparative",
    relatedPatterns: ["n1-054"],
  },
  {
    id: "n1-128",
    pattern: "～に先立って/に先立ち",
    meaning: "prior to; before",
    meaningJp: "～の前に",
    example: "開会に先立ち、注意事項を説明します。",
    exampleTranslation: "Prior to the opening, I will explain the precautions.",
    category: "temporal",
    relatedPatterns: [],
  },
  {
    id: "n1-129",
    pattern: "～ぶり",
    meaning: "way of; manner; after (time)",
    meaningJp: "～の様子",
    example: "3年ぶりに会った。",
    exampleTranslation: "I met them for the first time in 3 years.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-130",
    pattern: "～まみれ",
    meaning: "covered in; smeared with",
    meaningJp: "～だらけ",
    example: "泥まみれになった。",
    exampleTranslation: "I got covered in mud.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-131",
    pattern: "～もいいところだ",
    meaning: "completely; totally (negative emphasis)",
    meaningJp: "まさに～だ",
    example: "怠慢もいいところだ。",
    exampleTranslation: "It's complete negligence.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-132",
    pattern: "～もかまわず",
    meaning: "without caring about; regardless of",
    meaningJp: "～を気にせず",
    example: "人目もかまわず泣いた。",
    exampleTranslation: "They cried without caring about the attention.",
    category: "other",
    relatedPatterns: ["n1-109"],
  },
  {
    id: "n1-133",
    pattern: "～ようか～まいか",
    meaning: "whether to... or not",
    meaningJp: "～するかどうか",
    example: "行こうか行くまいか迷っている。",
    exampleTranslation: "I'm wondering whether to go or not.",
    category: "conditional",
    relatedPatterns: [],
  },
  {
    id: "n1-134",
    pattern: "～より致し方ない",
    meaning: "no choice but; cannot help",
    meaningJp: "～するしかない",
    example: "諦めるより致し方ない。",
    exampleTranslation: "There's no choice but to give up.",
    category: "formal",
    relatedPatterns: ["n1-112"],
  },
  {
    id: "n1-135",
    pattern: "～をいいことに",
    meaning: "taking advantage of",
    meaningJp: "～を良い機会として",
    example: "親がいないのをいいことに、遊び歩いている。",
    exampleTranslation: "Taking advantage of parents being away, they're out having fun.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-136",
    pattern: "～を経て",
    meaning: "through; via; after going through",
    meaningJp: "～を通して",
    example: "多くの困難を経て、成功した。",
    exampleTranslation: "After going through many difficulties, they succeeded.",
    category: "temporal",
    relatedPatterns: [],
  },
  {
    id: "n1-137",
    pattern: "～を踏まえて",
    meaning: "based on; considering",
    meaningJp: "～を考慮して",
    example: "前回の反省を踏まえて、改善した。",
    exampleTranslation: "Based on the reflection from last time, we improved.",
    category: "formal",
    relatedPatterns: [],
  },
  {
    id: "n1-138",
    pattern: "～んがばかりに",
    meaning: "as if to; on the verge of",
    meaningJp: "～しそうなほど",
    example: "泣き出さんばかりに訴えた。",
    exampleTranslation: "They pleaded as if about to cry.",
    category: "emphasis",
    relatedPatterns: ["n1-085"],
  },
  {
    id: "n1-139",
    pattern: "～以前の問題だ",
    meaning: "it's not even about... ; fundamentally wrong",
    meaningJp: "～より前の問題だ",
    example: "マナー以前の問題だ。",
    exampleTranslation: "It's not even about manners—it's fundamentally wrong.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-140",
    pattern: "～一方で",
    meaning: "on the other hand; while",
    meaningJp: "その反面",
    example: "便利な一方で、危険も伴う。",
    exampleTranslation: "While convenient, it also involves danger.",
    category: "conjunctive",
    relatedPatterns: [],
  },
  {
    id: "n1-141",
    pattern: "～折(に)/折から",
    meaning: "when; on the occasion of",
    meaningJp: "～の時に",
    example: "お近くにお越しの折には、お立ち寄りください。",
    exampleTranslation: "When you're nearby, please stop by.",
    category: "temporal",
    relatedPatterns: [],
  },
  {
    id: "n1-142",
    pattern: "～かねない",
    meaning: "might; could possibly (negative consequence)",
    meaningJp: "～する可能性がある",
    example: "事故につながりかねない。",
    exampleTranslation: "It could possibly lead to an accident.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-143",
    pattern: "～こそあれ",
    meaning: "although there may be; while there is",
    meaningJp: "～はあっても",
    example: "不満こそあれ、文句は言わない。",
    exampleTranslation: "Although there is dissatisfaction, I won't complain.",
    category: "conditional",
    relatedPatterns: [],
  },
  {
    id: "n1-144",
    pattern: "～ことなしに",
    meaning: "without",
    meaningJp: "～なしに",
    example: "努力することなしに、成功はない。",
    exampleTranslation: "Without effort, there is no success.",
    category: "conditional",
    relatedPatterns: ["n1-040"],
  },
  {
    id: "n1-145",
    pattern: "～ざるを得ない",
    meaning: "cannot help but; have no choice but",
    meaningJp: "～しなければならない",
    example: "認めざるを得ない。",
    exampleTranslation: "I have no choice but to acknowledge it.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-146",
    pattern: "～しまつだ",
    meaning: "ended up; resulted in (negative)",
    meaningJp: "結局～という悪い結果になった",
    example: "嘘がばれて、信用を失う始末だ。",
    exampleTranslation: "The lie was exposed, and they ended up losing trust.",
    category: "emphasis",
    relatedPatterns: ["n1-016"],
  },
  {
    id: "n1-147",
    pattern: "～すら/さえ～ない",
    meaning: "not even",
    meaningJp: "～でさえ～ない",
    example: "水すら飲めない。",
    exampleTranslation: "I can't even drink water.",
    category: "negative",
    relatedPatterns: ["n1-118"],
  },
  {
    id: "n1-148",
    pattern: "～そばから",
    meaning: "as soon as; right after (and immediately undone)",
    meaningJp: "～するとすぐに",
    example: "片付けるそばから散らかす。",
    exampleTranslation: "They make a mess as soon as I clean up.",
    category: "temporal",
    relatedPatterns: [],
  },
  {
    id: "n1-149",
    pattern: "～だに",
    meaning: "even just (thinking/imagining)",
    meaningJp: "～だけでも",
    example: "想像するだに恐ろしい。",
    exampleTranslation: "It's terrifying just to imagine.",
    category: "classical",
    relatedPatterns: [],
  },
  {
    id: "n1-150",
    pattern: "～っこない",
    meaning: "absolutely no way; impossible",
    meaningJp: "絶対～ない",
    example: "そんなこと、できっこない。",
    exampleTranslation: "There's absolutely no way I can do that.",
    category: "negative",
    relatedPatterns: [],
  },

  // ============================================================================
  // Additional Patterns (151-175)
  // ============================================================================
  {
    id: "n1-151",
    pattern: "～であれ～であれ",
    meaning: "whether... or...",
    meaningJp: "～でも～でも",
    example: "男であれ女であれ、平等に扱う。",
    exampleTranslation: "Whether male or female, we treat everyone equally.",
    category: "conditional",
    relatedPatterns: ["n1-024"],
  },
  {
    id: "n1-152",
    pattern: "～ではあるまいし",
    meaning: "it's not like; since it's not",
    meaningJp: "～ではないのだから",
    example: "子供ではあるまいし、泣くな。",
    exampleTranslation: "You're not a child, so don't cry.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-153",
    pattern: "～と思いきや",
    meaning: "just when you thought; contrary to expectations",
    meaningJp: "～と思ったら",
    example: "終わりかと思いきや、まだ続いた。",
    exampleTranslation: "Just when I thought it was over, it continued.",
    category: "conditional",
    relatedPatterns: [],
  },
  {
    id: "n1-154",
    pattern: "～ないでもない",
    meaning: "not that... isn't; somewhat",
    meaningJp: "～がないわけではない",
    example: "気持ちが分からないでもない。",
    exampleTranslation: "It's not that I don't understand your feelings.",
    category: "conditional",
    relatedPatterns: ["n1-098"],
  },
  {
    id: "n1-155",
    pattern: "～なくしては",
    meaning: "without",
    meaningJp: "～がなくては",
    example: "愛なくしては生きられない。",
    exampleTranslation: "One cannot live without love.",
    category: "conditional",
    relatedPatterns: ["n1-040"],
  },
  {
    id: "n1-156",
    pattern: "～にあたらない",
    meaning: "not worth; no need to",
    meaningJp: "～する必要はない",
    example: "驚くにあたらない。",
    exampleTranslation: "There's no need to be surprised.",
    category: "negative",
    relatedPatterns: [],
  },
  {
    id: "n1-157",
    pattern: "～に越したことはない",
    meaning: "nothing better than; best to",
    meaningJp: "～のが一番良い",
    example: "用心するに越したことはない。",
    exampleTranslation: "It's best to be careful.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-158",
    pattern: "～にしてからが",
    meaning: "even; if even... then",
    meaningJp: "～でさえ",
    example: "先生にしてからが分からない問題だ。",
    exampleTranslation: "Even the teacher doesn't understand this problem.",
    category: "emphasis",
    relatedPatterns: ["n1-099"],
  },
  {
    id: "n1-159",
    pattern: "～にして初めて",
    meaning: "only after; not until",
    meaningJp: "～して初めて",
    example: "失ってにして初めて気づく。",
    exampleTranslation: "You only realize after you've lost it.",
    category: "temporal",
    relatedPatterns: [],
  },
  {
    id: "n1-160",
    pattern: "～にせよ～にせよ",
    meaning: "whether... or...",
    meaningJp: "～にしても～にしても",
    example: "行くにせよ行かないにせよ、連絡してください。",
    exampleTranslation: "Whether you go or not, please contact me.",
    category: "conditional",
    relatedPatterns: ["n1-151"],
  },
  {
    id: "n1-161",
    pattern: "～にもほどがある",
    meaning: "there's a limit to; too much",
    meaningJp: "～にも限度がある",
    example: "冗談にもほどがある。",
    exampleTranslation: "There's a limit to joking.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-162",
    pattern: "～の念に堪えない",
    meaning: "cannot help but feel; deeply feel",
    meaningJp: "～の気持ちを抑えられない",
    example: "感謝の念に堪えない。",
    exampleTranslation: "I cannot help but feel grateful.",
    category: "formal",
    relatedPatterns: ["n1-100"],
  },
  {
    id: "n1-163",
    pattern: "～は措いて",
    meaning: "setting aside; leaving aside",
    meaningJp: "～は別として",
    example: "過去は措いて、未来を見よう。",
    exampleTranslation: "Setting aside the past, let's look to the future.",
    category: "other",
    relatedPatterns: ["n1-061"],
  },
  {
    id: "n1-164",
    pattern: "～びる",
    meaning: "to look like; to seem like",
    meaningJp: "～らしく見える",
    example: "大人びた話し方だ。",
    exampleTranslation: "Their way of speaking seems adult-like.",
    category: "other",
    relatedPatterns: ["n1-070"],
  },
  {
    id: "n1-165",
    pattern: "～ぶる",
    meaning: "to act like; to pretend to be",
    meaningJp: "～のふりをする",
    example: "知識人ぶる。",
    exampleTranslation: "To act like an intellectual.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-166",
    pattern: "～ほかはない",
    meaning: "have no choice but",
    meaningJp: "～するしかない",
    example: "受け入れるほかはない。",
    exampleTranslation: "There's no choice but to accept.",
    category: "other",
    relatedPatterns: ["n1-112"],
  },
  {
    id: "n1-167",
    pattern: "～までして",
    meaning: "going so far as to",
    meaningJp: "～までやって",
    example: "嘘をついてまでして、守りたいものがある。",
    exampleTranslation: "There's something I want to protect, even if it means lying.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-168",
    pattern: "～めいた",
    meaning: "seeming like; resembling",
    meaningJp: "～のような",
    example: "皮肉めいた笑いだ。",
    exampleTranslation: "A smile resembling irony.",
    category: "other",
    relatedPatterns: ["n1-070"],
  },
  {
    id: "n1-169",
    pattern: "～も同然だ",
    meaning: "as good as; practically",
    meaningJp: "～と同じだ",
    example: "約束を破ったも同然だ。",
    exampleTranslation: "It's as good as breaking a promise.",
    category: "comparative",
    relatedPatterns: [],
  },
  {
    id: "n1-170",
    pattern: "～ものとする",
    meaning: "shall; will be assumed",
    meaningJp: "～と決める",
    example: "規則に従うものとする。",
    exampleTranslation: "It shall be assumed that rules are followed.",
    category: "formal",
    relatedPatterns: [],
  },
  {
    id: "n1-171",
    pattern: "～ものと思われる",
    meaning: "it is thought that; considered to be",
    meaningJp: "～と考えられる",
    example: "成功するものと思われる。",
    exampleTranslation: "It is thought that it will succeed.",
    category: "formal",
    relatedPatterns: [],
  },
  {
    id: "n1-172",
    pattern: "～やら～やら",
    meaning: "things like... and...",
    meaningJp: "～とか～とか",
    example: "仕事やら家事やらで忙しい。",
    exampleTranslation: "I'm busy with work and housework and such.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-173",
    pattern: "～を押して/を押し切って",
    meaning: "despite; overcoming",
    meaningJp: "～を無理して",
    example: "反対を押し切って、実行した。",
    exampleTranslation: "Despite opposition, they carried it out.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-174",
    pattern: "～を契機に/を契機として",
    meaning: "taking the opportunity of; triggered by",
    meaningJp: "～をきっかけに",
    example: "結婚を契機に、仕事を辞めた。",
    exampleTranslation: "Taking the opportunity of marriage, they quit their job.",
    category: "temporal",
    relatedPatterns: [],
  },
  {
    id: "n1-175",
    pattern: "～を前にして",
    meaning: "in the face of; before",
    meaningJp: "～を目前にして",
    example: "死を前にして、過去を振り返った。",
    exampleTranslation: "In the face of death, they reflected on the past.",
    category: "temporal",
    relatedPatterns: [],
  },

  // ============================================================================
  // Final Patterns (176-200)
  // ============================================================================
  {
    id: "n1-176",
    pattern: "～を通じて/を通して",
    meaning: "through; throughout",
    meaningJp: "～を介して",
    example: "インターネットを通じて知り合った。",
    exampleTranslation: "We met through the internet.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-177",
    pattern: "～を頼りに",
    meaning: "relying on; depending on",
    meaningJp: "～を頼って",
    example: "記憶を頼りに道を探した。",
    exampleTranslation: "I searched for the way relying on my memory.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-178",
    pattern: "～を踏まえて",
    meaning: "based on; taking into account",
    meaningJp: "～を考慮して",
    example: "経験を踏まえて判断する。",
    exampleTranslation: "I make judgments based on experience.",
    category: "formal",
    relatedPatterns: ["n1-137"],
  },
  {
    id: "n1-179",
    pattern: "～んとする",
    meaning: "to be about to; to try to",
    meaningJp: "～しようとする",
    example: "飛び立たんとする鳥。",
    exampleTranslation: "A bird about to take flight.",
    category: "classical",
    relatedPatterns: [],
  },
  {
    id: "n1-180",
    pattern: "～如きは",
    meaning: "such a thing as; the likes of",
    meaningJp: "～のようなものは",
    example: "私如きが言うのも何ですが。",
    exampleTranslation: "It may not be my place to say, but...",
    category: "classical",
    relatedPatterns: ["n1-014"],
  },
  {
    id: "n1-181",
    pattern: "～手前",
    meaning: "considering; since (obligation)",
    meaningJp: "～という立場から",
    example: "約束した手前、断れない。",
    exampleTranslation: "Since I made a promise, I can't refuse.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-182",
    pattern: "～際(に)",
    meaning: "when; at the time of",
    meaningJp: "～の時に",
    example: "お帰りの際にはお忘れ物のないように。",
    exampleTranslation: "When leaving, please don't forget your belongings.",
    category: "temporal",
    relatedPatterns: ["n1-046"],
  },
  {
    id: "n1-183",
    pattern: "～限り(で)は",
    meaning: "as far as; as long as",
    meaningJp: "～する範囲では",
    example: "私の知る限りでは、彼は無実だ。",
    exampleTranslation: "As far as I know, he is innocent.",
    category: "conditional",
    relatedPatterns: [],
  },
  {
    id: "n1-184",
    pattern: "～と見える/と見えて",
    meaning: "apparently; it seems",
    meaningJp: "～らしく",
    example: "疲れていると見えて、すぐ寝てしまった。",
    exampleTranslation: "Apparently tired, they fell asleep immediately.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-185",
    pattern: "～と見るや",
    meaning: "no sooner... than; as soon as seeing",
    meaningJp: "～と思うとすぐに",
    example: "相手の弱みと見るや、攻撃してきた。",
    exampleTranslation: "As soon as they saw a weakness, they attacked.",
    category: "temporal",
    relatedPatterns: ["n1-012"],
  },
  {
    id: "n1-186",
    pattern: "～極める",
    meaning: "to reach the extreme of; to master",
    meaningJp: "～の極致に達する",
    example: "技術を極める。",
    exampleTranslation: "To master a technique.",
    category: "emphasis",
    relatedPatterns: ["n1-013"],
  },
  {
    id: "n1-187",
    pattern: "～足りない/足りる",
    meaning: "not enough to; sufficient to",
    meaningJp: "～には不足/十分だ",
    example: "説明するまでもなく分かるだろう。取るに足りない問題だ。",
    exampleTranslation: "It should be clear without explanation. It's a trivial problem.",
    category: "other",
    relatedPatterns: ["n1-053"],
  },
  {
    id: "n1-188",
    pattern: "～からある",
    meaning: "as much as; at least",
    meaningJp: "～もある",
    example: "10キロからある荷物を運んだ。",
    exampleTranslation: "I carried luggage weighing at least 10 kilos.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-189",
    pattern: "～からする/からして/からの",
    meaning: "costing/worth; from; judging from",
    meaningJp: "～以上の",
    example: "100万円からする時計を買った。",
    exampleTranslation: "I bought a watch costing over a million yen.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-190",
    pattern: "～きっての",
    meaning: "the foremost; the best",
    meaningJp: "～で一番の",
    example: "この町きっての名店だ。",
    exampleTranslation: "It's the foremost famous shop in this town.",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-191",
    pattern: "～ごときで/ぐらいで",
    meaning: "just because of; with mere",
    meaningJp: "～程度のことで",
    example: "こんなことごときで諦めない。",
    exampleTranslation: "I won't give up just because of something like this.",
    category: "emphasis",
    relatedPatterns: ["n1-014"],
  },
  {
    id: "n1-192",
    pattern: "～ずくめ",
    meaning: "entirely; all; nothing but",
    meaningJp: "全部～だ",
    example: "黒ずくめの服を着ている。",
    exampleTranslation: "They're wearing nothing but black.",
    category: "other",
    relatedPatterns: [],
  },
  {
    id: "n1-193",
    pattern: "～ずとも",
    meaning: "even without",
    meaningJp: "～しなくても",
    example: "言わずとも分かる。",
    exampleTranslation: "I understand even without you saying it.",
    category: "conditional",
    relatedPatterns: [],
  },
  {
    id: "n1-194",
    pattern: "～たり/たりとも",
    meaning: "even (one); not even",
    meaningJp: "一つも",
    example: "一歩たりとも引かない。",
    exampleTranslation: "I won't retreat even a single step.",
    category: "negative",
    relatedPatterns: ["n1-019"],
  },
  {
    id: "n1-195",
    pattern: "～であれ",
    meaning: "even if; whoever",
    meaningJp: "たとえ～でも",
    example: "何人であれ、例外はない。",
    exampleTranslation: "Whoever it is, there are no exceptions.",
    category: "conditional",
    relatedPatterns: ["n1-024"],
  },
  {
    id: "n1-196",
    pattern: "～でもって",
    meaning: "with; by means of",
    meaningJp: "～で",
    example: "誠意でもって対応する。",
    exampleTranslation: "I will respond with sincerity.",
    category: "formal",
    relatedPatterns: ["n1-080"],
  },
  {
    id: "n1-197",
    pattern: "～とばかり(に)",
    meaning: "as if to say; seemingly",
    meaningJp: "～と言わんばかりに",
    example: "待ってましたとばかりに飛び出した。",
    exampleTranslation: "They rushed out as if to say 'I've been waiting.'",
    category: "emphasis",
    relatedPatterns: [],
  },
  {
    id: "n1-198",
    pattern: "～とみるや",
    meaning: "as soon as judging",
    meaningJp: "～と分かるとすぐに",
    example: "チャンスとみるや、行動に移した。",
    exampleTranslation: "As soon as they judged it was a chance, they took action.",
    category: "temporal",
    relatedPatterns: ["n1-185"],
  },
  {
    id: "n1-199",
    pattern: "～ながらの",
    meaning: "while remaining; as it is",
    meaningJp: "～のままの",
    example: "昔ながらの味だ。",
    exampleTranslation: "It's a taste from the old days.",
    category: "other",
    relatedPatterns: ["n1-039"],
  },
  {
    id: "n1-200",
    pattern: "～ならまだしも",
    meaning: "if it were... it might be acceptable, but",
    meaningJp: "～ならまだ良いが",
    example: "一回ならまだしも、何度もは許せない。",
    exampleTranslation: "Once might be acceptable, but many times is unforgivable.",
    category: "conditional",
    relatedPatterns: ["n1-126"],
  },
];

async function seed() {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    console.error("DATABASE_URL not set");
    process.exit(1);
  }

  const pool = new pg.Pool({ connectionString });
  const db = drizzle(pool);

  console.log("Seeding 200 JLPT N1 grammar patterns...");

  for (const pattern of n1GrammarPatterns) {
    try {
      await db.insert(grammarPoints).values(pattern).onConflictDoNothing();
      console.log(`  ✓ ${pattern.id}: ${pattern.pattern}`);
    } catch (error) {
      console.error(`  ✗ ${pattern.id}: ${error}`);
    }
  }

  console.log(`\nSeeded ${n1GrammarPatterns.length} grammar patterns.`);
  await pool.end();
}

seed().catch(console.error);
