import { Link } from "wouter";
import { motion } from "framer-motion";
import { Clapperboard, MonitorPlay } from "lucide-react";

export default function RoleSelection() {
  return (
    <div className="min-h-[calc(100vh-64px)] flex items-center justify-center p-4">
      <div className="grid md:grid-cols-2 gap-8 max-w-4xl w-full">
        <RoleCard
          href="/create"
          title="Creator"
          icon={Clapperboard}
          desc="Select grammar patterns and unleash AI agents to find matching clips."
          color="border-primary"
          bg="hover:bg-primary/5"
          text="text-primary"
        />
        <RoleCard
          href="/watch"
          title="Watcher"
          icon={MonitorPlay}
          desc="Browse the curated feed of grammar-focused clips generated by the community."
          color="border-secondary"
          bg="hover:bg-secondary/5"
          text="text-secondary"
        />
      </div>
    </div>
  );
}

function RoleCard({ href, title, icon: Icon, desc, color, bg, text }: any) {
  return (
    <Link href={href}>
      <motion.a
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        className={`block p-12 h-80 rounded-xl border-2 ${color} ${bg} bg-card/50 backdrop-blur-sm cursor-pointer transition-all flex flex-col items-center justify-center text-center group`}
      >
        <div className={`mb-6 p-4 rounded-full bg-background border ${color}`}>
          <Icon className={`w-12 h-12 ${text}`} />
        </div>
        <h2 className="text-3xl font-serif font-bold mb-4">{title}</h2>
        <p className="text-muted-foreground max-w-xs mx-auto">{desc}</p>
        <div className={`mt-8 font-mono text-sm ${text} opacity-0 group-hover:opacity-100 transition-opacity`}>
          INITIALIZE_MODULE &gt;&gt;
        </div>
      </motion.a>
    </Link>
  );
}
